name: test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Prerequisites
        run: |
          sudo apt install php-cli php-mysql php-dom mysql-server sqlite3
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          curl -o composer.phar https://getcomposer.org/installer
          git clone https://github.com/dirtsimple/postmark
          curl -O -L https://github.com/elementor/wp2static/archive/refs/tags/7.2.tar.gz
      
      - name: Test
        run: |
          sudo service mysql start
          sudo mysql -h 127.0.0.1 --user=root --password=root <<< "CREATE USER 'wpssguser'@'127.0.0.1' IDENTIFIED WITH mysql_native_password BY 'wpssgpass'; CREATE DATABASE wpssgdb; GRANT ALL PRIVILEGES ON wpssgdb.* TO 'wpssguser'@'127.0.0.1';"
          sudo mysql -h 127.0.0.1 --user=wpssguser --password=wpssgpass <<< "SHOW DATABASES"

          php ./wp-cli.phar core download --locale=en_US #  --skip-content --force
          php ./wp-cli.phar config create --locale=en_US --dbuser=wpssguser --dbpass=wpssgpass --dbname=wpssgdb --dbhost=127.0.0.1
          #php ./wp-cli.phar db create
          php ./wp-cli.phar core install --url=localhost:8080 --title=wpcli --admin_user=wpcli --admin_password=wpcli --admin_email=info@wp-cli.org
          php ./wp-cli.phar option set permalink_structure '/%year%-%monthnum%-%day%-%postname%/'
          php ./wp-cli.phar theme install --activate https://knd.te-st.ru/kandinsky.zip
          
          find

          mkdir -p ./wp-content/plugins/wp2static # php wp-cli.phar plugin path
          tar -xf 7.2.tar.gz -C ./wp-content/plugins/wp2static --strip-components=1
          cd ./wp-content/plugins/wp2static
          php ../../../composer.phar install
          php ../../../composer.phar update
          php ../../../composer.phar install --quiet --no-dev --optimize-autoloader
          cd  ../../../

          php ./wp-cli.phar plugin activate wp2static
          php ./wp-cli.phar wp2static options set deploymentURL http://localhost:8080/
          #php ./wp-cli.phar wp2static detect
          #php ./wp-cli.phar wp2static crawl
          #php ./wp-cli.phar wp2static post_process

          #cp postmark_composer.json postmark/composer.json
          #sed -i 's@League\\CommonMark\\Ext\\Table\\TableExtension@dirtsimple\\Postmark\\ShortcodeParser@g' ./postmark/src/Formatter.php
          #sed -i 's@League\\CommonMark\\Ext\\Strikethrough\\StrikethroughExtension@dirtsimple\\Postmark\\ShortcodeParser@g' ./postmark/src/Formatter.php
          #sed -i 's@League\\CommonMark\\Ext\\SmartPunct\\SmartPunctExtension@dirtsimple\\Postmark\\ShortcodeParser@g' ./postmark/src/Formatter.php
          #sed -i 's@Webuni\\CommonMark\\AttributesExtension\\AttributesExtension@dirtsimple\\Postmark\\ShortcodeParser@g' ./postmark/src/Formatter.php
          #php ./wp-cli.phar package install ./postmark

          #php ./wp-cli.phar post list --post_type=page --field=url
          #php ./wp-cli.phar post list --post_type=post --field=url
          #php ./wp-cli.phar server --host=localhost --port=8080 &
          #curl http://127.0.0.1:8080
       
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: wp-content/uploads/wp2static-processed-site/
